"""create_all_remaining_tables

Revision ID: 105bfd055cd6
Revises: cc5e9bd6b409
Create Date: 2025-11-11 23:34:22.596631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105bfd055cd6'
down_revision: Union[str, Sequence[str], None] = 'cc5e9bd6b409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_templates',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='模板ID'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('title_template', sa.String(length=200), nullable=True, comment='标题模板'),
    sa.Column('description_template', sa.Text(), nullable=True, comment='描述模板'),
    sa.Column('default_recurrence_type', sa.String(length=20), nullable=True, comment='默认周期类型'),
    sa.Column('default_recurrence_config', sa.JSON(), nullable=True, comment='默认周期配置'),
    sa.Column('default_advance_days', sa.Integer(), nullable=True, comment='默认提前天数'),
    sa.Column('suggested_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='建议金额'),
    sa.Column('suggested_attachments', sa.JSON(), nullable=True, comment='建议附件'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='是否系统模板'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_templates_category'), 'reminder_templates', ['category'], unique=False)
    op.create_index(op.f('ix_reminder_templates_id'), 'reminder_templates', ['id'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='配置ID'),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.JSON(), nullable=False, comment='配置值JSON'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置描述'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table('family_groups',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='家庭组ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='家庭组名称'),
    sa.Column('creator_id', sa.BigInteger(), nullable=False, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_groups_id'), 'family_groups', ['id'], unique=False)
    op.create_table('template_shares',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='分享ID'),
    sa.Column('template_id', sa.BigInteger(), nullable=False, comment='模板ID(关联user_custom_templates或reminder_templates)'),
    sa.Column('template_type', sa.String(length=20), nullable=False, comment='模板类型: user_custom, system'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='所有者ID'),
    sa.Column('share_type', sa.String(length=20), nullable=False, comment='分享类型: public, family, private_link'),
    sa.Column('share_code', sa.String(length=10), nullable=False, comment='分享码'),
    sa.Column('share_title', sa.String(length=200), nullable=True, comment='分享标题'),
    sa.Column('share_description', sa.Text(), nullable=True, comment='分享描述'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='点赞数'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_shares_id'), 'template_shares', ['id'], unique=False)
    op.create_index(op.f('ix_template_shares_share_code'), 'template_shares', ['share_code'], unique=True)
    op.create_index(op.f('ix_template_shares_share_type'), 'template_shares', ['share_type'], unique=False)
    op.create_table('user_behaviors',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('behavior_date', sa.Date(), nullable=False, comment='行为日期'),
    sa.Column('active_hours', sa.JSON(), nullable=True, comment='活跃时段JSON数组'),
    sa.Column('confirm_avg_response_minutes', sa.Integer(), nullable=True, comment='平均响应时间(分钟)'),
    sa.Column('completion_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='完成率'),
    sa.Column('most_used_categories', sa.JSON(), nullable=True, comment='最常用分类JSON数组'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'behavior_date', name='uq_user_behavior_date')
    )
    op.create_index(op.f('ix_user_behaviors_id'), 'user_behaviors', ['id'], unique=False)
    op.create_table('user_custom_templates',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='模板ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('title_template', sa.String(length=200), nullable=True, comment='标题模板'),
    sa.Column('description_template', sa.Text(), nullable=True, comment='描述模板'),
    sa.Column('recurrence_type', sa.String(length=20), nullable=True, comment='周期类型'),
    sa.Column('recurrence_config', sa.JSON(), nullable=True, comment='周期配置'),
    sa.Column('advance_days', sa.Integer(), nullable=True, comment='提前天数'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类'),
    sa.Column('created_from_template_id', sa.BigInteger(), nullable=True, comment='来源模板ID'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_from_template_id'], ['reminder_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_custom_templates_id'), 'user_custom_templates', ['id'], unique=False)
    op.create_index(op.f('ix_user_custom_templates_user_id'), 'user_custom_templates', ['user_id'], unique=False)
    op.create_table('voice_inputs',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('audio_url', sa.String(length=255), nullable=True, comment='音频URL'),
    sa.Column('recognized_text', sa.Text(), nullable=True, comment='识别文本'),
    sa.Column('parsed_result', sa.JSON(), nullable=True, comment='解析结果JSON'),
    sa.Column('is_successful', sa.Boolean(), nullable=True, comment='是否成功'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_inputs_id'), 'voice_inputs', ['id'], unique=False)
    op.create_index(op.f('ix_voice_inputs_user_id'), 'voice_inputs', ['user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='成员记录ID'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='家庭组ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role', sa.String(length=20), nullable=True, comment='角色: admin, member, viewer'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='加入时间'),
    sa.ForeignKeyConstraint(['group_id'], ['family_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_user')
    )
    op.create_index(op.f('ix_family_members_id'), 'family_members', ['id'], unique=False)
    op.create_table('template_likes',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='点赞ID'),
    sa.Column('template_share_id', sa.BigInteger(), nullable=False, comment='分享ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='点赞时间'),
    sa.ForeignKeyConstraint(['template_share_id'], ['template_shares.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_share_id', 'user_id', name='uq_template_user_like')
    )
    op.create_index(op.f('ix_template_likes_id'), 'template_likes', ['id'], unique=False)
    op.create_table('reminder_completions',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='记录ID'),
    sa.Column('reminder_id', sa.BigInteger(), nullable=False, comment='提醒ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False, comment='计划时间'),
    sa.Column('completed_time', sa.DateTime(timezone=True), nullable=False, comment='完成时间'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: completed, delayed, skipped'),
    sa.Column('delay_minutes', sa.Integer(), nullable=True, comment='延迟分钟数'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_completions_id'), 'reminder_completions', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_completions_reminder_id'), 'reminder_completions', ['reminder_id'], unique=False)
    op.create_index(op.f('ix_reminder_completions_scheduled_time'), 'reminder_completions', ['scheduled_time'], unique=False)
    op.create_table('template_usage_records',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='记录ID'),
    sa.Column('template_share_id', sa.BigInteger(), nullable=False, comment='分享ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='使用者ID'),
    sa.Column('reminder_id', sa.BigInteger(), nullable=True, comment='创建的提醒ID'),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='使用时间'),
    sa.Column('feedback_rating', sa.Integer(), nullable=True, comment='评分1-5'),
    sa.Column('feedback_comment', sa.Text(), nullable=True, comment='评价内容'),
    sa.CheckConstraint('feedback_rating >= 1 AND feedback_rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['template_share_id'], ['template_shares.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_usage_records_id'), 'template_usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_template_usage_records_template_share_id'), 'template_usage_records', ['template_share_id'], unique=False)
    op.create_index(op.f('ix_template_usage_records_user_id'), 'template_usage_records', ['user_id'], unique=False)
    op.create_table('push_logs',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='日志ID'),
    sa.Column('task_id', sa.BigInteger(), nullable=True, comment='推送任务ID'),
    sa.Column('reminder_id', sa.BigInteger(), nullable=False, comment='提醒ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('push_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='推送时间'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='推送渠道: app, sms, wechat, call'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: success, failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('user_action', sa.String(length=20), nullable=True, comment='用户操作: confirmed, ignored, delayed, dismissed'),
    sa.Column('user_action_time', sa.DateTime(timezone=True), nullable=True, comment='用户操作时间'),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True, comment='响应时间(秒)'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['push_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_logs_id'), 'push_logs', ['id'], unique=False)
    op.create_index(op.f('ix_push_logs_push_time'), 'push_logs', ['push_time'], unique=False)
    op.create_index(op.f('ix_push_logs_reminder_id'), 'push_logs', ['reminder_id'], unique=False)
    op.add_column('reminders', sa.Column('family_group_id', sa.Integer(), nullable=True, comment='家庭组ID'))
    op.add_column('reminders', sa.Column('template_id', sa.Integer(), nullable=True, comment='模板ID'))
    op.create_index(op.f('ix_reminders_family_group_id'), 'reminders', ['family_group_id'], unique=False)
    op.create_foreign_key(None, 'reminders', 'reminder_templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'reminders', 'family_groups', ['family_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_index(op.f('ix_reminders_family_group_id'), table_name='reminders')
    op.drop_column('reminders', 'template_id')
    op.drop_column('reminders', 'family_group_id')
    op.drop_index(op.f('ix_push_logs_reminder_id'), table_name='push_logs')
    op.drop_index(op.f('ix_push_logs_push_time'), table_name='push_logs')
    op.drop_index(op.f('ix_push_logs_id'), table_name='push_logs')
    op.drop_table('push_logs')
    op.drop_index(op.f('ix_template_usage_records_user_id'), table_name='template_usage_records')
    op.drop_index(op.f('ix_template_usage_records_template_share_id'), table_name='template_usage_records')
    op.drop_index(op.f('ix_template_usage_records_id'), table_name='template_usage_records')
    op.drop_table('template_usage_records')
    op.drop_index(op.f('ix_reminder_completions_scheduled_time'), table_name='reminder_completions')
    op.drop_index(op.f('ix_reminder_completions_reminder_id'), table_name='reminder_completions')
    op.drop_index(op.f('ix_reminder_completions_id'), table_name='reminder_completions')
    op.drop_table('reminder_completions')
    op.drop_index(op.f('ix_template_likes_id'), table_name='template_likes')
    op.drop_table('template_likes')
    op.drop_index(op.f('ix_family_members_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_voice_inputs_user_id'), table_name='voice_inputs')
    op.drop_index(op.f('ix_voice_inputs_id'), table_name='voice_inputs')
    op.drop_table('voice_inputs')
    op.drop_index(op.f('ix_user_custom_templates_user_id'), table_name='user_custom_templates')
    op.drop_index(op.f('ix_user_custom_templates_id'), table_name='user_custom_templates')
    op.drop_table('user_custom_templates')
    op.drop_index(op.f('ix_user_behaviors_id'), table_name='user_behaviors')
    op.drop_table('user_behaviors')
    op.drop_index(op.f('ix_template_shares_share_type'), table_name='template_shares')
    op.drop_index(op.f('ix_template_shares_share_code'), table_name='template_shares')
    op.drop_index(op.f('ix_template_shares_id'), table_name='template_shares')
    op.drop_table('template_shares')
    op.drop_index(op.f('ix_family_groups_id'), table_name='family_groups')
    op.drop_table('family_groups')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_reminder_templates_id'), table_name='reminder_templates')
    op.drop_index(op.f('ix_reminder_templates_category'), table_name='reminder_templates')
    op.drop_table('reminder_templates')
    # ### end Alembic commands ###
