"""Update models to SQLAlchemy 2.0 syntax

Revision ID: 21e5c66fa535
Revises: 85748611ec83
Create Date: 2025-11-14 14:51:01.683949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21e5c66fa535'
down_revision: Union[str, Sequence[str], None] = '85748611ec83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 数据修复：在设置 NOT NULL 约束之前，先更新所有 NULL 值
    op.execute("UPDATE family_groups SET is_active = TRUE WHERE is_active IS NULL")
    op.execute("UPDATE family_members SET is_active = TRUE WHERE is_active IS NULL")
    op.execute("UPDATE push_tasks SET priority = 1 WHERE priority IS NULL")
    op.execute("UPDATE push_tasks SET channels = '[]' WHERE channels IS NULL")
    op.execute("UPDATE push_tasks SET retry_count = 0 WHERE retry_count IS NULL")
    op.execute("UPDATE push_tasks SET max_retries = 3 WHERE max_retries IS NULL")
    op.execute("UPDATE reminder_completions SET delay_minutes = 0 WHERE delay_minutes IS NULL")
    op.execute("UPDATE reminder_templates SET default_advance_days = 3 WHERE default_advance_days IS NULL")
    op.execute("UPDATE reminder_templates SET is_system = TRUE WHERE is_system IS NULL")
    op.execute("UPDATE reminder_templates SET usage_count = 0 WHERE usage_count IS NULL")
    op.execute("UPDATE reminders SET priority = 1 WHERE priority IS NULL")
    op.execute("UPDATE reminders SET recurrence_config = '{}' WHERE recurrence_config IS NULL")
    op.execute("UPDATE reminders SET remind_channels = '[]' WHERE remind_channels IS NULL")
    op.execute("UPDATE reminders SET advance_minutes = 0 WHERE advance_minutes IS NULL")
    op.execute("UPDATE reminders SET is_active = TRUE WHERE is_active IS NULL")
    op.execute("UPDATE reminders SET is_completed = FALSE WHERE is_completed IS NULL")
    op.execute("UPDATE template_shares SET template_id = 0 WHERE template_id IS NULL")  # 这个可能需要手动处理
    op.execute("UPDATE template_shares SET usage_count = 0 WHERE usage_count IS NULL")
    op.execute("UPDATE template_shares SET like_count = 0 WHERE like_count IS NULL")
    op.execute("UPDATE template_shares SET is_active = TRUE WHERE is_active IS NULL")
    op.execute("UPDATE user_custom_templates SET usage_count = 0 WHERE usage_count IS NULL")
    op.execute("UPDATE users SET settings = '{}' WHERE settings IS NULL")
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL")
    op.execute("UPDATE voice_inputs SET is_successful = FALSE WHERE is_successful IS NULL")
    
    op.alter_column('family_groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否有效')
    op.alter_column('family_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('family_members', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MEMBER', 'VIEWER', name='memberrole'),
               nullable=False,
               existing_comment='角色')
    op.alter_column('family_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否激活')
    op.alter_column('family_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='加入时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('push_logs', 'reminder_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='提醒ID')
    op.alter_column('push_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='用户ID')
    op.alter_column('push_logs', 'push_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='推送时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('push_logs', 'user_action_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='用户操作时间',
               existing_nullable=True)
    op.alter_column('push_tasks', 'channels',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_comment='推送渠道(JSON)')
    op.alter_column('push_tasks', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='优先级: 1=普通, 2=重要, 3=紧急',
               existing_comment='优先级')
    op.alter_column('push_tasks', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='计划推送时间',
               existing_nullable=False)
    op.alter_column('push_tasks', 'sent_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='实际发送时间',
               existing_nullable=True)
    op.alter_column('push_tasks', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='pushstatus'),
               nullable=False,
               existing_comment='推送状态')
    op.alter_column('push_tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='重试次数')
    op.alter_column('push_tasks', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='最大重试次数')
    op.alter_column('push_tasks', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='执行时间',
               existing_nullable=True)
    op.alter_column('push_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('push_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('reminder_completions', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='计划时间',
               existing_nullable=True)
    op.alter_column('reminder_completions', 'completed_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='实际完成时间',
               existing_nullable=False)
    op.alter_column('reminder_completions', 'status',
               existing_type=postgresql.ENUM('COMPLETED', 'DELAYED', 'SKIPPED', 'MISSED', name='completionstatus'),
               nullable=False,
               existing_comment='状态')
    op.alter_column('reminder_completions', 'delay_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='延迟分钟数')
    op.alter_column('reminder_completions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('reminder_templates', 'default_advance_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='默认提前天数')
    op.alter_column('reminder_templates', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否系统模板')
    op.alter_column('reminder_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='使用次数')
    op.alter_column('reminder_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='优先级: 1=普通, 2=重要, 3=紧急')
    op.alter_column('reminders', 'recurrence_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_comment='周期配置(JSON)')
    op.alter_column('reminders', 'first_remind_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='首次提醒时间',
               existing_nullable=False)
    op.alter_column('reminders', 'next_remind_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='下次提醒时间',
               existing_nullable=False)
    op.alter_column('reminders', 'last_remind_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='上次提醒时间',
               existing_nullable=True)
    op.alter_column('reminders', 'remind_channels',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_comment='提醒渠道(JSON): app, sms, wechat, call')
    op.alter_column('reminders', 'advance_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='提前提醒分钟数')
    op.alter_column('reminders', 'amount',
               existing_type=sa.INTEGER(),
               comment='金额(分)',
               existing_comment='金额（以分为单位）',
               existing_nullable=True)
    op.alter_column('reminders', 'location',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='位置信息',
               existing_comment='位置信息(JSON)',
               existing_nullable=True)
    op.alter_column('reminders', 'attachments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='附件列表',
               existing_comment='附件列表(JSON)',
               existing_nullable=True)
    op.alter_column('reminders', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否启用')
    op.alter_column('reminders', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否已完成')
    op.alter_column('reminders', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('system_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('template_likes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='点赞时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('template_shares', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='用户模板ID')
    op.alter_column('template_shares', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='使用次数')
    op.alter_column('template_shares', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='点赞数')
    op.alter_column('template_shares', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否有效')
    op.alter_column('template_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('template_shares', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='过期时间',
               existing_nullable=True)
    op.alter_column('template_usage_records', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='使用时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('user_behaviors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('user_custom_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='使用次数')
    op.alter_column('user_custom_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_comment='用户设置(JSON)')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否激活')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_inputs', 'is_successful',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否成功')
    op.alter_column('voice_inputs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_inputs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_inputs', 'is_successful',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否成功')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否激活')
    op.alter_column('users', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_comment='用户设置(JSON)')
    op.alter_column('user_custom_templates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('user_custom_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='使用次数')
    op.alter_column('user_behaviors', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('template_usage_records', 'used_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='使用时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('template_shares', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='过期时间',
               existing_nullable=True)
    op.alter_column('template_shares', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('template_shares', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否有效')
    op.alter_column('template_shares', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='点赞数')
    op.alter_column('template_shares', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='使用次数')
    op.alter_column('template_shares', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='用户模板ID')
    op.alter_column('template_likes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='点赞时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('system_configs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('reminders', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否已完成')
    op.alter_column('reminders', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否启用')
    op.alter_column('reminders', 'attachments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='附件列表(JSON)',
               existing_comment='附件列表',
               existing_nullable=True)
    op.alter_column('reminders', 'location',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='位置信息(JSON)',
               existing_comment='位置信息',
               existing_nullable=True)
    op.alter_column('reminders', 'amount',
               existing_type=sa.INTEGER(),
               comment='金额（以分为单位）',
               existing_comment='金额(分)',
               existing_nullable=True)
    op.alter_column('reminders', 'advance_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='提前提醒分钟数')
    op.alter_column('reminders', 'remind_channels',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_comment='提醒渠道(JSON): app, sms, wechat, call')
    op.alter_column('reminders', 'last_remind_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='上次提醒时间',
               existing_nullable=True)
    op.alter_column('reminders', 'next_remind_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='下次提醒时间',
               existing_nullable=False)
    op.alter_column('reminders', 'first_remind_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='首次提醒时间',
               existing_nullable=False)
    op.alter_column('reminders', 'recurrence_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_comment='周期配置(JSON)')
    op.alter_column('reminders', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='优先级: 1=普通, 2=重要, 3=紧急')
    op.alter_column('reminder_templates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('reminder_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='使用次数')
    op.alter_column('reminder_templates', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否系统模板')
    op.alter_column('reminder_templates', 'default_advance_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='默认提前天数')
    op.alter_column('reminder_completions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('reminder_completions', 'delay_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='延迟分钟数')
    op.alter_column('reminder_completions', 'status',
               existing_type=postgresql.ENUM('COMPLETED', 'DELAYED', 'SKIPPED', 'MISSED', name='completionstatus'),
               nullable=True,
               existing_comment='状态')
    op.alter_column('reminder_completions', 'completed_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='实际完成时间',
               existing_nullable=False)
    op.alter_column('reminder_completions', 'scheduled_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='计划时间',
               existing_nullable=True)
    op.alter_column('push_tasks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('push_tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('push_tasks', 'executed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='执行时间',
               existing_nullable=True)
    op.alter_column('push_tasks', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='最大重试次数')
    op.alter_column('push_tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='重试次数')
    op.alter_column('push_tasks', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='pushstatus'),
               nullable=True,
               existing_comment='推送状态')
    op.alter_column('push_tasks', 'sent_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='实际发送时间',
               existing_nullable=True)
    op.alter_column('push_tasks', 'scheduled_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='计划推送时间',
               existing_nullable=False)
    op.alter_column('push_tasks', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='优先级',
               existing_comment='优先级: 1=普通, 2=重要, 3=紧急')
    op.alter_column('push_tasks', 'channels',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_comment='推送渠道(JSON)')
    op.alter_column('push_logs', 'user_action_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='用户操作时间',
               existing_nullable=True)
    op.alter_column('push_logs', 'push_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='推送时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('push_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='用户ID')
    op.alter_column('push_logs', 'reminder_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='提醒ID')
    op.alter_column('family_members', 'joined_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='加入时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('family_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否激活')
    op.alter_column('family_members', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MEMBER', 'VIEWER', name='memberrole'),
               nullable=True,
               existing_comment='角色')
    op.alter_column('family_groups', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('family_groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否有效')
    # ### end Alembic commands ###
