"""optimize_amount_and_location_fields

Revision ID: 60a176a40e72
Revises: change_category_to_string
Create Date: 2025-12-28 23:11:19.695610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60a176a40e72'
down_revision: Union[str, Sequence[str], None] = 'change_category_to_string'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('notes', sa.String(length=500), nullable=True, comment='备注信息'))
    op.alter_column('reminders', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='分类（用户可自定义）',
               existing_nullable=False)
    
    # 第1步：将 amount 从 INT (分) 转换为临时列
    op.add_column('reminders', sa.Column('amount_temp', sa.Float(), nullable=True))
    
    # 第2步：数据迁移 - 将分转换为元 (除以100)
    op.execute("""
        UPDATE reminders 
        SET amount_temp = CASE 
            WHEN amount IS NOT NULL THEN amount::float / 100.0
            ELSE NULL 
        END
    """)
    
    # 第3步：删除旧列，重命名新列
    op.drop_column('reminders', 'amount')
    op.alter_column('reminders', 'amount_temp', new_column_name='amount')
    op.alter_column('reminders', 'amount',
               existing_type=sa.Float(),
               comment='金额(元)',
               existing_nullable=True)
    
    # 第4步：处理 location - 从 JSON 提取 address 字段
    op.add_column('reminders', sa.Column('location_temp', sa.String(length=200), nullable=True))
    
    # 数据迁移 - 提取 JSON 中的 address 字段
    op.execute("""
        UPDATE reminders 
        SET location_temp = CASE 
            WHEN location IS NOT NULL AND location->>'address' IS NOT NULL 
            THEN location->>'address'
            ELSE NULL 
        END
    """)
    
    # 第5步：删除旧 location，重命名新列
    op.drop_column('reminders', 'location')
    op.alter_column('reminders', 'location_temp', new_column_name='location')
    op.alter_column('reminders', 'location',
               existing_type=sa.String(length=200),
               comment='位置信息(文本地址)',
               existing_nullable=True)
    
    # 删除 attachments 字段
    op.drop_column('reminders', 'attachments')
    
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               comment='用户角色',
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::userrole"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               comment=None,
               existing_comment='用户角色',
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::userrole"))
    
    # 恢复 attachments
    op.add_column('reminders', sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='附件列表'))
    
    # 恢复 location 为 JSON 类型
    op.add_column('reminders', sa.Column('location_old', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # 将文本地址包装为 JSON
    op.execute("""
        UPDATE reminders 
        SET location_old = CASE 
            WHEN location IS NOT NULL THEN json_build_object('address', location)
            ELSE NULL 
        END
    """)
    op.drop_column('reminders', 'location')
    op.alter_column('reminders', 'location_old', new_column_name='location')
    op.alter_column('reminders', 'location',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='位置信息',
               existing_nullable=True)
    
    # 恢复 amount 为 INT (分)
    op.add_column('reminders', sa.Column('amount_old', sa.INTEGER(), nullable=True))
    # 将元转换回分 (乘以100)
    op.execute("""
        UPDATE reminders 
        SET amount_old = CASE 
            WHEN amount IS NOT NULL THEN ROUND(amount * 100)::integer
            ELSE NULL 
        END
    """)
    op.drop_column('reminders', 'amount')
    op.alter_column('reminders', 'amount_old', new_column_name='amount')
    op.alter_column('reminders', 'amount',
               existing_type=sa.INTEGER(),
               comment='金额(分)',
               existing_nullable=True)
    
    op.alter_column('reminders', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='分类（用户可自定义）',
               existing_nullable=False)
    op.drop_column('reminders', 'notes')
    # ### end Alembic commands ###
