"""initial_migration

Revision ID: 7ad7168b373a
Revises: 
Create Date: 2025-11-20 15:32:01.968558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ad7168b373a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_templates',
    sa.Column('id', sa.Integer(), nullable=False, comment='模板ID'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('title_template', sa.String(length=200), nullable=True, comment='标题模板'),
    sa.Column('description_template', sa.Text(), nullable=True, comment='描述模板'),
    sa.Column('default_recurrence_type', sa.String(length=20), nullable=True, comment='默认周期类型'),
    sa.Column('default_recurrence_config', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='默认周期配置'),
    sa.Column('default_advance_days', sa.Integer(), nullable=False, comment='默认提前天数'),
    sa.Column('suggested_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='建议金额'),
    sa.Column('suggested_attachments', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='建议附件'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否系统模板'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='使用次数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_templates_category'), 'reminder_templates', ['category'], unique=False)
    op.create_index(op.f('ix_reminder_templates_id'), 'reminder_templates', ['id'], unique=False)
    op.create_table('sms_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='日志ID'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='接收手机号'),
    sa.Column('purpose', sa.String(length=20), nullable=False, comment='用途: register, reset, verify'),
    sa.Column('code', sa.String(length=10), nullable=False, comment='验证码（加密或脱敏存储）'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='请求IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending, sent, failed'),
    sa.Column('provider', sa.String(length=20), nullable=True, comment='短信提供商: aliyun, noop'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='是否已验证'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='验证时间'),
    sa.Column('verify_attempts', sa.Integer(), nullable=False, comment='尝试验证次数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='发送时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ip_created', 'sms_logs', ['ip_address', 'created_at'], unique=False)
    op.create_index('idx_phone_purpose_created', 'sms_logs', ['phone', 'purpose', 'created_at'], unique=False)
    op.create_index(op.f('ix_sms_logs_created_at'), 'sms_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sms_logs_expires_at'), 'sms_logs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sms_logs_id'), 'sms_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sms_logs_phone'), 'sms_logs', ['phone'], unique=False)
    op.create_index(op.f('ix_sms_logs_purpose'), 'sms_logs', ['purpose'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False, comment='配置ID'),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='配置值(JSON)'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置描述'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('settings', sa.JSON(), nullable=False, comment='用户设置(JSON)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('family_groups',
    sa.Column('id', sa.Integer(), nullable=False, comment='家庭组ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='家庭组名称'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_groups_id'), 'family_groups', ['id'], unique=False)
    op.create_table('user_behaviors',
    sa.Column('id', sa.Integer(), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('behavior_date', sa.Date(), nullable=False, comment='行为日期'),
    sa.Column('active_hours', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='活跃时段(JSON): [8, 9, 18, 19, 20]'),
    sa.Column('confirm_avg_response_minutes', sa.Integer(), nullable=True, comment='平均响应时间(分钟)'),
    sa.Column('completion_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='完成率'),
    sa.Column('most_used_categories', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment="常用分类(JSON): ['rent', 'health']"),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'behavior_date', name='uq_user_behavior_date')
    )
    op.create_index(op.f('ix_user_behaviors_id'), 'user_behaviors', ['id'], unique=False)
    op.create_table('user_custom_templates',
    sa.Column('id', sa.Integer(), nullable=False, comment='模板ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('title_template', sa.String(length=200), nullable=True, comment='标题模板'),
    sa.Column('description_template', sa.Text(), nullable=True, comment='描述模板'),
    sa.Column('recurrence_type', sa.String(length=20), nullable=True, comment='周期类型'),
    sa.Column('recurrence_config', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='周期配置'),
    sa.Column('advance_days', sa.Integer(), nullable=True, comment='提前天数'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类'),
    sa.Column('created_from_template_id', sa.Integer(), nullable=True, comment='基于的系统模板ID'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='使用次数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_from_template_id'], ['reminder_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_custom_templates_id'), 'user_custom_templates', ['id'], unique=False)
    op.create_table('voice_inputs',
    sa.Column('id', sa.Integer(), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('audio_url', sa.String(length=255), nullable=True, comment='音频文件URL'),
    sa.Column('recognized_text', sa.Text(), nullable=True, comment='识别文本'),
    sa.Column('parsed_result', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='解析结果(JSON)'),
    sa.Column('is_successful', sa.Boolean(), nullable=False, comment='是否成功'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_inputs_id'), 'voice_inputs', ['id'], unique=False)
    op.create_index(op.f('ix_voice_inputs_user_id'), 'voice_inputs', ['user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False, comment='成员关系ID'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='家庭组ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', 'VIEWER', name='memberrole'), nullable=False, comment='角色'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='在家庭组中的昵称'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='加入时间'),
    sa.ForeignKeyConstraint(['group_id'], ['family_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_user')
    )
    op.create_index(op.f('ix_family_members_id'), 'family_members', ['id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False, comment='提醒ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('family_group_id', sa.Integer(), nullable=True, comment='家庭组ID'),
    sa.Column('template_id', sa.Integer(), nullable=True, comment='模板ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='提醒标题'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='提醒描述'),
    sa.Column('category', sa.Enum('RENT', 'HEALTH', 'PET', 'FINANCE', 'DOCUMENT', 'MEMORIAL', 'OTHER', name='remindercategory'), nullable=False, comment='分类'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级: 1=普通, 2=重要, 3=紧急'),
    sa.Column('recurrence_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM', name='recurrencetype'), nullable=False, comment='周期类型'),
    sa.Column('recurrence_config', sa.JSON(), nullable=False, comment='周期配置(JSON)'),
    sa.Column('first_remind_time', sa.DateTime(), nullable=False, comment='首次提醒时间'),
    sa.Column('next_remind_time', sa.DateTime(), nullable=False, comment='下次提醒时间'),
    sa.Column('last_remind_time', sa.DateTime(), nullable=True, comment='上次提醒时间'),
    sa.Column('remind_channels', sa.JSON(), nullable=False, comment='提醒渠道(JSON): app, sms, wechat, call'),
    sa.Column('advance_minutes', sa.Integer(), nullable=False, comment='提前提醒分钟数'),
    sa.Column('amount', sa.Integer(), nullable=True, comment='金额(分)'),
    sa.Column('location', sa.JSON(), nullable=True, comment='位置信息'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件列表'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='是否已完成'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['family_group_id'], ['family_groups.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['reminder_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_family_group_id'), 'reminders', ['family_group_id'], unique=False)
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_index(op.f('ix_reminders_is_active'), 'reminders', ['is_active'], unique=False)
    op.create_index(op.f('ix_reminders_next_remind_time'), 'reminders', ['next_remind_time'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('template_shares',
    sa.Column('id', sa.Integer(), nullable=False, comment='分享ID'),
    sa.Column('template_id', sa.Integer(), nullable=False, comment='用户模板ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='分享者ID'),
    sa.Column('share_type', sa.Enum('PUBLIC', 'FAMILY', 'PRIVATE_LINK', name='sharetype'), nullable=False, comment='分享类型'),
    sa.Column('family_group_id', sa.Integer(), nullable=True, comment='家庭组ID（仅家庭分享）'),
    sa.Column('share_code', sa.String(length=10), nullable=False, comment='分享码'),
    sa.Column('share_title', sa.String(length=200), nullable=True, comment='分享标题'),
    sa.Column('share_description', sa.Text(), nullable=True, comment='分享描述'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='使用次数'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.ForeignKeyConstraint(['family_group_id'], ['family_groups.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['user_custom_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_shares_id'), 'template_shares', ['id'], unique=False)
    op.create_index(op.f('ix_template_shares_share_code'), 'template_shares', ['share_code'], unique=True)
    op.create_index(op.f('ix_template_shares_share_type'), 'template_shares', ['share_type'], unique=False)
    op.create_table('push_tasks',
    sa.Column('id', sa.Integer(), nullable=False, comment='任务ID'),
    sa.Column('reminder_id', sa.Integer(), nullable=False, comment='关联提醒ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='推送标题'),
    sa.Column('content', sa.String(length=500), nullable=True, comment='推送内容'),
    sa.Column('channels', sa.JSON(), nullable=False, comment='推送渠道(JSON)'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级: 1=普通, 2=重要, 3=紧急'),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False, comment='计划推送时间'),
    sa.Column('sent_time', sa.DateTime(), nullable=True, comment='实际发送时间'),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='pushstatus'), nullable=False, comment='推送状态'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='错误信息'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='最大重试次数'),
    sa.Column('executed_at', sa.DateTime(), nullable=True, comment='执行时间'),
    sa.Column('push_response', sa.JSON(), nullable=True, comment='推送服务响应(JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_tasks_id'), 'push_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_push_tasks_reminder_id'), 'push_tasks', ['reminder_id'], unique=False)
    op.create_index(op.f('ix_push_tasks_scheduled_time'), 'push_tasks', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_push_tasks_status'), 'push_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_push_tasks_user_id'), 'push_tasks', ['user_id'], unique=False)
    op.create_table('reminder_completions',
    sa.Column('id', sa.Integer(), nullable=False, comment='完成记录ID'),
    sa.Column('reminder_id', sa.Integer(), nullable=False, comment='提醒ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='完成用户ID'),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True, comment='计划时间'),
    sa.Column('completed_time', sa.DateTime(), nullable=False, comment='实际完成时间'),
    sa.Column('status', sa.Enum('COMPLETED', 'DELAYED', 'SKIPPED', 'MISSED', name='completionstatus'), nullable=False, comment='状态'),
    sa.Column('delay_minutes', sa.Integer(), nullable=False, comment='延迟分钟数'),
    sa.Column('note', sa.String(length=500), nullable=True, comment='完成备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_completions_completed_time'), 'reminder_completions', ['completed_time'], unique=False)
    op.create_index(op.f('ix_reminder_completions_id'), 'reminder_completions', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_completions_reminder_id'), 'reminder_completions', ['reminder_id'], unique=False)
    op.create_index(op.f('ix_reminder_completions_user_id'), 'reminder_completions', ['user_id'], unique=False)
    op.create_table('reminder_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('advance_notify_enabled', sa.Boolean(), nullable=False, comment='是否启用提前通知'),
    sa.Column('advance_days', sa.Integer(), nullable=False, comment='提前几天开始通知（如生日提前5天）'),
    sa.Column('advance_notify_interval', sa.Integer(), nullable=False, comment='提前通知间隔天数（如每2天通知一次）'),
    sa.Column('advance_notify_time', sa.String(length=5), nullable=False, comment='提前通知时间（HH:MM格式）'),
    sa.Column('same_day_notifications', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment="当天通知时间列表 ['08:00', '12:00', '20:00']"),
    sa.Column('avoid_night_time', sa.Boolean(), nullable=False, comment='避免夜间通知（22:00-07:00）'),
    sa.Column('night_time_fallback', sa.String(length=5), nullable=False, comment='夜间时间回退到的时间'),
    sa.Column('custom_message_template', sa.Text(), nullable=True, comment='自定义通知消息模板'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_notifications_id'), 'reminder_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_notifications_reminder_id'), 'reminder_notifications', ['reminder_id'], unique=True)
    op.create_table('template_likes',
    sa.Column('id', sa.Integer(), nullable=False, comment='点赞ID'),
    sa.Column('template_share_id', sa.Integer(), nullable=False, comment='分享模板ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='点赞用户ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='点赞时间'),
    sa.ForeignKeyConstraint(['template_share_id'], ['template_shares.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_share_id', 'user_id', name='uq_template_user_like')
    )
    op.create_index(op.f('ix_template_likes_id'), 'template_likes', ['id'], unique=False)
    op.create_table('template_usage_records',
    sa.Column('id', sa.Integer(), nullable=False, comment='记录ID'),
    sa.Column('template_share_id', sa.Integer(), nullable=False, comment='分享模板ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='使用者ID'),
    sa.Column('reminder_id', sa.Integer(), nullable=True, comment='创建的提醒ID'),
    sa.Column('used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='使用时间'),
    sa.Column('feedback_rating', sa.Integer(), nullable=True, comment='评分 1-5'),
    sa.Column('feedback_comment', sa.Text(), nullable=True, comment='评价内容'),
    sa.CheckConstraint('feedback_rating >= 1 AND feedback_rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['template_share_id'], ['template_shares.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_usage_records_id'), 'template_usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_template_usage_records_template_share_id'), 'template_usage_records', ['template_share_id'], unique=False)
    op.create_index(op.f('ix_template_usage_records_user_id'), 'template_usage_records', ['user_id'], unique=False)
    op.create_table('family_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_group_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('REMINDER_COMPLETED', 'REMINDER_CREATED', 'REMINDER_UPDATED', 'REMINDER_DELETED', 'MEMBER_JOINED', 'MEMBER_LEFT', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('related_reminder_id', sa.Integer(), nullable=True),
    sa.Column('related_completion_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_group_id'], ['family_groups.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_completion_id'], ['reminder_completions.id'], ),
    sa.ForeignKeyConstraint(['related_reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_notifications_family_group_id'), 'family_notifications', ['family_group_id'], unique=False)
    op.create_index(op.f('ix_family_notifications_id'), 'family_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_family_notifications_is_read'), 'family_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_family_notifications_receiver_id'), 'family_notifications', ['receiver_id'], unique=False)
    op.create_table('push_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='日志ID'),
    sa.Column('task_id', sa.Integer(), nullable=True, comment='推送任务ID'),
    sa.Column('reminder_id', sa.Integer(), nullable=False, comment='提醒ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('push_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='推送时间'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='推送渠道: app, sms, wechat, call'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='推送状态: success, failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('user_action', sa.String(length=20), nullable=True, comment='用户操作: confirmed, ignored, delayed, dismissed'),
    sa.Column('user_action_time', sa.DateTime(), nullable=True, comment='用户操作时间'),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True, comment='响应时间(秒)'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['push_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_logs_id'), 'push_logs', ['id'], unique=False)
    op.create_index(op.f('ix_push_logs_push_time'), 'push_logs', ['push_time'], unique=False)
    op.create_index(op.f('ix_push_logs_reminder_id'), 'push_logs', ['reminder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_logs_reminder_id'), table_name='push_logs')
    op.drop_index(op.f('ix_push_logs_push_time'), table_name='push_logs')
    op.drop_index(op.f('ix_push_logs_id'), table_name='push_logs')
    op.drop_table('push_logs')
    op.drop_index(op.f('ix_family_notifications_receiver_id'), table_name='family_notifications')
    op.drop_index(op.f('ix_family_notifications_is_read'), table_name='family_notifications')
    op.drop_index(op.f('ix_family_notifications_id'), table_name='family_notifications')
    op.drop_index(op.f('ix_family_notifications_family_group_id'), table_name='family_notifications')
    op.drop_table('family_notifications')
    op.drop_index(op.f('ix_template_usage_records_user_id'), table_name='template_usage_records')
    op.drop_index(op.f('ix_template_usage_records_template_share_id'), table_name='template_usage_records')
    op.drop_index(op.f('ix_template_usage_records_id'), table_name='template_usage_records')
    op.drop_table('template_usage_records')
    op.drop_index(op.f('ix_template_likes_id'), table_name='template_likes')
    op.drop_table('template_likes')
    op.drop_index(op.f('ix_reminder_notifications_reminder_id'), table_name='reminder_notifications')
    op.drop_index(op.f('ix_reminder_notifications_id'), table_name='reminder_notifications')
    op.drop_table('reminder_notifications')
    op.drop_index(op.f('ix_reminder_completions_user_id'), table_name='reminder_completions')
    op.drop_index(op.f('ix_reminder_completions_reminder_id'), table_name='reminder_completions')
    op.drop_index(op.f('ix_reminder_completions_id'), table_name='reminder_completions')
    op.drop_index(op.f('ix_reminder_completions_completed_time'), table_name='reminder_completions')
    op.drop_table('reminder_completions')
    op.drop_index(op.f('ix_push_tasks_user_id'), table_name='push_tasks')
    op.drop_index(op.f('ix_push_tasks_status'), table_name='push_tasks')
    op.drop_index(op.f('ix_push_tasks_scheduled_time'), table_name='push_tasks')
    op.drop_index(op.f('ix_push_tasks_reminder_id'), table_name='push_tasks')
    op.drop_index(op.f('ix_push_tasks_id'), table_name='push_tasks')
    op.drop_table('push_tasks')
    op.drop_index(op.f('ix_template_shares_share_type'), table_name='template_shares')
    op.drop_index(op.f('ix_template_shares_share_code'), table_name='template_shares')
    op.drop_index(op.f('ix_template_shares_id'), table_name='template_shares')
    op.drop_table('template_shares')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_next_remind_time'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_is_active'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_family_group_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_family_members_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_voice_inputs_user_id'), table_name='voice_inputs')
    op.drop_index(op.f('ix_voice_inputs_id'), table_name='voice_inputs')
    op.drop_table('voice_inputs')
    op.drop_index(op.f('ix_user_custom_templates_id'), table_name='user_custom_templates')
    op.drop_table('user_custom_templates')
    op.drop_index(op.f('ix_user_behaviors_id'), table_name='user_behaviors')
    op.drop_table('user_behaviors')
    op.drop_index(op.f('ix_family_groups_id'), table_name='family_groups')
    op.drop_table('family_groups')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_sms_logs_purpose'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_phone'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_id'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_expires_at'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_created_at'), table_name='sms_logs')
    op.drop_index('idx_phone_purpose_created', table_name='sms_logs')
    op.drop_index('idx_ip_created', table_name='sms_logs')
    op.drop_table('sms_logs')
    op.drop_index(op.f('ix_reminder_templates_id'), table_name='reminder_templates')
    op.drop_index(op.f('ix_reminder_templates_category'), table_name='reminder_templates')
    op.drop_table('reminder_templates')
    # ### end Alembic commands ###
