"""Add family notifications table

Revision ID: 7ef22acacd62
Revises: a222ba72c6e8
Create Date: 2025-11-13 23:47:19.635829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ef22acacd62'
down_revision: Union[str, Sequence[str], None] = 'a222ba72c6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ip_created'), table_name='sms_logs')
    op.drop_index(op.f('idx_phone_purpose_created'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_created_at'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_expires_at'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_id'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_phone'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_purpose'), table_name='sms_logs')
    op.drop_table('sms_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='接收手机号'),
    sa.Column('purpose', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='用途: register, reset, verify'),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='验证码（加密或脱敏存储）'),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='请求IP地址'),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True, comment='用户代理'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='状态: pending, sent, failed'),
    sa.Column('provider', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='短信提供商: aliyun, noop'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='错误信息'),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否已验证'),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='验证时间'),
    sa.Column('verify_attempts', sa.INTEGER(), autoincrement=False, nullable=True, comment='尝试验证次数'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='发送时间'),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='过期时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sms_logs_pkey'))
    )
    op.create_index(op.f('ix_sms_logs_purpose'), 'sms_logs', ['purpose'], unique=False)
    op.create_index(op.f('ix_sms_logs_phone'), 'sms_logs', ['phone'], unique=False)
    op.create_index(op.f('ix_sms_logs_id'), 'sms_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sms_logs_expires_at'), 'sms_logs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sms_logs_created_at'), 'sms_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_phone_purpose_created'), 'sms_logs', ['phone', 'purpose', 'created_at'], unique=False)
    op.create_index(op.f('idx_ip_created'), 'sms_logs', ['ip_address', 'created_at'], unique=False)
    # ### end Alembic commands ###
