"""Add reminder notifications config table

Revision ID: 85748611ec83
Revises: 7ef22acacd62
Create Date: 2025-11-13 23:50:12.871134

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '85748611ec83'
down_revision: Union[str, Sequence[str], None] = '7ef22acacd62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
