"""fix_model_relationships_and_add_shares

Revision ID: 959712c6c00a
Revises: 105bfd055cd6
Create Date: 2025-11-12 13:31:55.311693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '959712c6c00a'
down_revision: Union[str, Sequence[str], None] = '105bfd055cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types first
    memberrole_enum = postgresql.ENUM('ADMIN', 'MEMBER', 'VIEWER', name='memberrole', create_type=False)
    memberrole_enum.create(op.get_bind(), checkfirst=True)
    
    completionstatus_enum = postgresql.ENUM('COMPLETED', 'DELAYED', 'SKIPPED', 'MISSED', name='completionstatus', create_type=False)
    completionstatus_enum.create(op.get_bind(), checkfirst=True)
    
    sharetype_enum = postgresql.ENUM('PUBLIC', 'FAMILY', 'PRIVATE_LINK', name='sharetype', create_type=False)
    sharetype_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('family_groups', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='家庭组ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('family_groups_id_seq'::regclass)"))
    op.alter_column('family_groups', 'creator_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='创建者ID',
               existing_nullable=False)
    op.alter_column('family_groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否有效',
               existing_comment='是否激活',
               existing_nullable=True)
    op.add_column('family_members', sa.Column('nickname', sa.String(length=50), nullable=True, comment='在家庭组中的昵称'))
    op.add_column('family_members', sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'))
    op.alter_column('family_members', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               comment='成员关系ID',
               existing_comment='成员记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('family_members', 'group_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='家庭组ID',
               existing_nullable=False)
    op.alter_column('family_members', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=False)
    # Convert role column to enum - first update data to uppercase
    op.execute("UPDATE family_members SET role = UPPER(role)")
    op.execute("ALTER TABLE family_members ALTER COLUMN role TYPE memberrole USING role::memberrole")
    op.execute("COMMENT ON COLUMN family_members.role IS '角色'")
    op.alter_column('push_logs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='日志ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('push_logs', 'task_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='推送任务ID',
               existing_nullable=True)
    op.alter_column('push_logs', 'reminder_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_comment='提醒ID')
    op.alter_column('push_logs', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_comment='用户ID')
    op.alter_column('push_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='推送状态: success, failed',
               existing_comment='状态: success, failed',
               existing_nullable=False)
    op.alter_column('push_tasks', 'priority',
               existing_type=sa.INTEGER(),
               comment='优先级',
               existing_comment='优先级: 1=普通, 2=重要, 3=紧急',
               existing_nullable=True)
    op.alter_column('push_tasks', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='执行时间',
               existing_nullable=True)
    op.alter_column('reminder_completions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               comment='完成记录ID',
               existing_comment='记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('reminder_completions', 'reminder_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='提醒ID',
               existing_nullable=False)
    op.alter_column('reminder_completions', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               comment='完成用户ID',
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('reminder_completions', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='计划时间')
    op.alter_column('reminder_completions', 'completed_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='实际完成时间',
               existing_comment='完成时间',
               existing_nullable=False)
    # Convert status column to enum - first update data to uppercase
    op.execute("UPDATE reminder_completions SET status = UPPER(status)")
    op.execute("ALTER TABLE reminder_completions ALTER COLUMN status TYPE completionstatus USING status::completionstatus")
    op.execute("COMMENT ON COLUMN reminder_completions.status IS '状态'")
    op.alter_column('reminder_completions', 'note',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               comment='完成备注',
               existing_comment='备注',
               existing_nullable=True)
    op.drop_index(op.f('ix_reminder_completions_scheduled_time'), table_name='reminder_completions')
    op.create_index(op.f('ix_reminder_completions_completed_time'), 'reminder_completions', ['completed_time'], unique=False)
    op.create_index(op.f('ix_reminder_completions_user_id'), 'reminder_completions', ['user_id'], unique=False)
    op.alter_column('reminder_templates', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='模板ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('reminder_templates_id_seq'::regclass)"))
    op.alter_column('system_configs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='配置ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('system_configs', 'config_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='配置值(JSON)',
               existing_comment='配置值JSON',
               existing_nullable=False)
    op.alter_column('template_likes', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='点赞ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('template_likes', 'template_share_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               comment='分享模板ID',
               existing_comment='分享ID',
               existing_nullable=False)
    op.alter_column('template_likes', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               comment='点赞用户ID',
               existing_comment='用户ID',
               existing_nullable=False)
    op.add_column('template_shares', sa.Column('user_id', sa.Integer(), nullable=False, comment='分享者ID'))
    op.add_column('template_shares', sa.Column('family_group_id', sa.Integer(), nullable=True, comment='家庭组ID（仅家庭分享）'))
    op.alter_column('template_shares', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='分享ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('template_shares_id_seq'::regclass)"))
    op.alter_column('template_shares', 'template_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               comment='用户模板ID',
               existing_comment='模板ID(关联user_custom_templates或reminder_templates)')
    # Convert share_type column to enum - first update data to uppercase  
    op.execute("UPDATE template_shares SET share_type = UPPER(share_type)")
    op.execute("ALTER TABLE template_shares ALTER COLUMN share_type TYPE sharetype USING share_type::sharetype")
    op.execute("COMMENT ON COLUMN template_shares.share_type IS '分享类型'")
    op.alter_column('template_shares', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否有效',
               existing_comment='是否激活',
               existing_nullable=True)
    op.drop_constraint(op.f('template_shares_owner_id_fkey'), 'template_shares', type_='foreignkey')
    op.create_foreign_key(None, 'template_shares', 'family_groups', ['family_group_id'], ['id'])
    op.create_foreign_key(None, 'template_shares', 'user_custom_templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'template_shares', 'users', ['user_id'], ['id'])
    op.drop_column('template_shares', 'template_type')
    op.drop_column('template_shares', 'owner_id')
    op.alter_column('template_usage_records', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('template_usage_records', 'template_share_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               comment='分享模板ID',
               existing_comment='分享ID',
               existing_nullable=False)
    op.alter_column('template_usage_records', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='使用者ID',
               existing_nullable=False)
    op.alter_column('template_usage_records', 'reminder_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='创建的提醒ID',
               existing_nullable=True)
    op.alter_column('template_usage_records', 'feedback_rating',
               existing_type=sa.INTEGER(),
               comment='评分 1-5',
               existing_comment='评分1-5',
               existing_nullable=True)
    op.alter_column('user_behaviors', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_behaviors', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_behaviors', 'active_hours',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='活跃时段(JSON): [8, 9, 18, 19, 20]',
               existing_comment='活跃时段JSON数组',
               existing_nullable=True)
    op.alter_column('user_behaviors', 'most_used_categories',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="常用分类(JSON): ['rent', 'health']",
               existing_comment='最常用分类JSON数组',
               existing_nullable=True)
    op.alter_column('user_custom_templates', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='模板ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_custom_templates', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_custom_templates', 'created_from_template_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               comment='基于的系统模板ID',
               existing_comment='来源模板ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_user_custom_templates_user_id'), table_name='user_custom_templates')
    op.alter_column('voice_inputs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('voice_inputs', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('voice_inputs', 'audio_url',
               existing_type=sa.VARCHAR(length=255),
               comment='音频文件URL',
               existing_comment='音频URL',
               existing_nullable=True)
    op.alter_column('voice_inputs', 'parsed_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='解析结果(JSON)',
               existing_comment='解析结果JSON',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_inputs', 'parsed_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='解析结果JSON',
               existing_comment='解析结果(JSON)',
               existing_nullable=True)
    op.alter_column('voice_inputs', 'audio_url',
               existing_type=sa.VARCHAR(length=255),
               comment='音频URL',
               existing_comment='音频文件URL',
               existing_nullable=True)
    op.alter_column('voice_inputs', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('voice_inputs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_user_custom_templates_user_id'), 'user_custom_templates', ['user_id'], unique=False)
    op.alter_column('user_custom_templates', 'created_from_template_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               comment='来源模板ID',
               existing_comment='基于的系统模板ID',
               existing_nullable=True)
    op.alter_column('user_custom_templates', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_custom_templates', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='模板ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_behaviors', 'most_used_categories',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='最常用分类JSON数组',
               existing_comment="常用分类(JSON): ['rent', 'health']",
               existing_nullable=True)
    op.alter_column('user_behaviors', 'active_hours',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='活跃时段JSON数组',
               existing_comment='活跃时段(JSON): [8, 9, 18, 19, 20]',
               existing_nullable=True)
    op.alter_column('user_behaviors', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_behaviors', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('template_usage_records', 'feedback_rating',
               existing_type=sa.INTEGER(),
               comment='评分1-5',
               existing_comment='评分 1-5',
               existing_nullable=True)
    op.alter_column('template_usage_records', 'reminder_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='创建的提醒ID',
               existing_nullable=True)
    op.alter_column('template_usage_records', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='使用者ID',
               existing_nullable=False)
    op.alter_column('template_usage_records', 'template_share_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               comment='分享ID',
               existing_comment='分享模板ID',
               existing_nullable=False)
    op.alter_column('template_usage_records', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.add_column('template_shares', sa.Column('owner_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='所有者ID'))
    op.add_column('template_shares', sa.Column('template_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='模板类型: user_custom, system'))
    op.drop_constraint(None, 'template_shares', type_='foreignkey')
    op.drop_constraint(None, 'template_shares', type_='foreignkey')
    op.drop_constraint(None, 'template_shares', type_='foreignkey')
    op.create_foreign_key(op.f('template_shares_owner_id_fkey'), 'template_shares', 'users', ['owner_id'], ['id'])
    op.alter_column('template_shares', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活',
               existing_comment='是否有效',
               existing_nullable=True)
    op.alter_column('template_shares', 'share_type',
               existing_type=sa.Enum('PUBLIC', 'FAMILY', 'PRIVATE_LINK', name='sharetype'),
               type_=sa.VARCHAR(length=20),
               comment='分享类型: public, family, private_link',
               existing_comment='分享类型',
               existing_nullable=False)
    op.alter_column('template_shares', 'template_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False,
               comment='模板ID(关联user_custom_templates或reminder_templates)',
               existing_comment='用户模板ID')
    op.alter_column('template_shares', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='分享ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('template_shares_id_seq'::regclass)"))
    op.drop_column('template_shares', 'family_group_id')
    op.drop_column('template_shares', 'user_id')
    op.alter_column('template_likes', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               comment='用户ID',
               existing_comment='点赞用户ID',
               existing_nullable=False)
    op.alter_column('template_likes', 'template_share_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               comment='分享ID',
               existing_comment='分享模板ID',
               existing_nullable=False)
    op.alter_column('template_likes', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='点赞ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('system_configs', 'config_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='配置值JSON',
               existing_comment='配置值(JSON)',
               existing_nullable=False)
    op.alter_column('system_configs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='配置ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('reminder_templates', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='模板ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('reminder_templates_id_seq'::regclass)"))
    op.drop_index(op.f('ix_reminder_completions_user_id'), table_name='reminder_completions')
    op.drop_index(op.f('ix_reminder_completions_completed_time'), table_name='reminder_completions')
    op.create_index(op.f('ix_reminder_completions_scheduled_time'), 'reminder_completions', ['scheduled_time'], unique=False)
    op.alter_column('reminder_completions', 'note',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               comment='备注',
               existing_comment='完成备注',
               existing_nullable=True)
    op.alter_column('reminder_completions', 'status',
               existing_type=sa.Enum('COMPLETED', 'DELAYED', 'SKIPPED', 'MISSED', name='completionstatus'),
               type_=sa.VARCHAR(length=20),
               comment='状态: completed, delayed, skipped',
               existing_comment='状态',
               existing_nullable=True)
    op.alter_column('reminder_completions', 'completed_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='完成时间',
               existing_comment='实际完成时间',
               existing_nullable=False)
    op.alter_column('reminder_completions', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='计划时间')
    op.alter_column('reminder_completions', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               comment='用户ID',
               existing_comment='完成用户ID',
               existing_nullable=False)
    op.alter_column('reminder_completions', 'reminder_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='提醒ID',
               existing_nullable=False)
    op.alter_column('reminder_completions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               comment='记录ID',
               existing_comment='完成记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('push_tasks', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='执行时间',
               existing_nullable=True)
    op.alter_column('push_tasks', 'priority',
               existing_type=sa.INTEGER(),
               comment='优先级: 1=普通, 2=重要, 3=紧急',
               existing_comment='优先级',
               existing_nullable=True)
    op.alter_column('push_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: success, failed',
               existing_comment='推送状态: success, failed',
               existing_nullable=False)
    op.alter_column('push_logs', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False,
               existing_comment='用户ID')
    op.alter_column('push_logs', 'reminder_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False,
               existing_comment='提醒ID')
    op.alter_column('push_logs', 'task_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='推送任务ID',
               existing_nullable=True)
    op.alter_column('push_logs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='日志ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('family_members', 'role',
               existing_type=sa.Enum('ADMIN', 'MEMBER', 'VIEWER', name='memberrole'),
               type_=sa.VARCHAR(length=20),
               comment='角色: admin, member, viewer',
               existing_comment='角色',
               existing_nullable=True)
    op.alter_column('family_members', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('family_members', 'group_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='家庭组ID',
               existing_nullable=False)
    op.alter_column('family_members', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               comment='成员记录ID',
               existing_comment='成员关系ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('family_members', 'is_active')
    op.drop_column('family_members', 'nickname')
    op.alter_column('family_groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活',
               existing_comment='是否有效',
               existing_nullable=True)
    op.alter_column('family_groups', 'creator_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='创建者ID',
               existing_nullable=False)
    op.alter_column('family_groups', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_comment='家庭组ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('family_groups_id_seq'::regclass)"))
    # ### end Alembic commands ###
