"""Initial migration

Revision ID: a44df02083fd
Revises: 
Create Date: 2025-11-11 13:17:21.249960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44df02083fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='用户设置(JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False, comment='提醒ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='提醒标题'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='提醒描述'),
    sa.Column('category', sa.Enum('RENT', 'HEALTH', 'PET', 'FINANCE', 'DOCUMENT', 'MEMORIAL', 'OTHER', name='remindercategory'), nullable=False, comment='分类'),
    sa.Column('recurrence_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM', name='recurrencetype'), nullable=False, comment='周期类型'),
    sa.Column('recurrence_config', sa.JSON(), nullable=True, comment='周期配置(JSON)'),
    sa.Column('first_remind_time', sa.DateTime(timezone=True), nullable=False, comment='首次提醒时间'),
    sa.Column('next_remind_time', sa.DateTime(timezone=True), nullable=False, comment='下次提醒时间'),
    sa.Column('last_remind_time', sa.DateTime(timezone=True), nullable=True, comment='上次提醒时间'),
    sa.Column('remind_channels', sa.JSON(), nullable=True, comment='提醒渠道(JSON): app, sms, wechat, call'),
    sa.Column('advance_minutes', sa.Integer(), nullable=True, comment='提前提醒分钟数'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_index(op.f('ix_reminders_is_active'), 'reminders', ['is_active'], unique=False)
    op.create_index(op.f('ix_reminders_next_remind_time'), 'reminders', ['next_remind_time'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('push_tasks',
    sa.Column('id', sa.Integer(), nullable=False, comment='任务ID'),
    sa.Column('reminder_id', sa.Integer(), nullable=False, comment='关联提醒ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='推送标题'),
    sa.Column('content', sa.String(length=500), nullable=True, comment='推送内容'),
    sa.Column('channels', sa.JSON(), nullable=True, comment='推送渠道(JSON)'),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False, comment='计划推送时间'),
    sa.Column('sent_time', sa.DateTime(timezone=True), nullable=True, comment='实际发送时间'),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='pushstatus'), nullable=True, comment='推送状态'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='错误信息'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='重试次数'),
    sa.Column('push_response', sa.JSON(), nullable=True, comment='推送服务响应(JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_tasks_id'), 'push_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_push_tasks_reminder_id'), 'push_tasks', ['reminder_id'], unique=False)
    op.create_index(op.f('ix_push_tasks_scheduled_time'), 'push_tasks', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_push_tasks_status'), 'push_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_push_tasks_user_id'), 'push_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_tasks_user_id'), table_name='push_tasks')
    op.drop_index(op.f('ix_push_tasks_status'), table_name='push_tasks')
    op.drop_index(op.f('ix_push_tasks_scheduled_time'), table_name='push_tasks')
    op.drop_index(op.f('ix_push_tasks_reminder_id'), table_name='push_tasks')
    op.drop_index(op.f('ix_push_tasks_id'), table_name='push_tasks')
    op.drop_table('push_tasks')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_next_remind_time'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_is_active'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
