"""update_models_to_match_design

Revision ID: cc5e9bd6b409
Revises: a44df02083fd
Create Date: 2025-11-11 23:10:44.880477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5e9bd6b409'
down_revision: Union[str, Sequence[str], None] = 'a44df02083fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_tasks', sa.Column('priority', sa.Integer(), nullable=True, comment='优先级: 1=普通, 2=重要, 3=紧急'))
    op.add_column('push_tasks', sa.Column('max_retries', sa.Integer(), nullable=True, comment='最大重试次数'))
    op.alter_column('push_tasks', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='推送标题',
               existing_nullable=False)
    op.add_column('reminders', sa.Column('priority', sa.Integer(), nullable=True, comment='优先级: 1=普通, 2=重要, 3=紧急'))
    op.add_column('reminders', sa.Column('amount', sa.Integer(), nullable=True, comment='金额（以分为单位）'))
    op.add_column('reminders', sa.Column('location', sa.JSON(), nullable=True, comment='位置信息(JSON)'))
    op.add_column('reminders', sa.Column('attachments', sa.JSON(), nullable=True, comment='附件列表(JSON)'))
    op.add_column('reminders', sa.Column('is_completed', sa.Boolean(), nullable=True, comment='是否已完成'))
    op.add_column('reminders', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'))
    op.alter_column('reminders', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='提醒标题',
               existing_nullable=False)
    op.alter_column('reminders', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_comment='提醒描述',
               existing_nullable=True)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.alter_column('reminders', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_comment='提醒描述',
               existing_nullable=True)
    op.alter_column('reminders', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_comment='提醒标题',
               existing_nullable=False)
    op.drop_column('reminders', 'completed_at')
    op.drop_column('reminders', 'is_completed')
    op.drop_column('reminders', 'attachments')
    op.drop_column('reminders', 'location')
    op.drop_column('reminders', 'amount')
    op.drop_column('reminders', 'priority')
    op.alter_column('push_tasks', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_comment='推送标题',
               existing_nullable=False)
    op.drop_column('push_tasks', 'max_retries')
    op.drop_column('push_tasks', 'priority')
    # ### end Alembic commands ###
